keycloak:
  jwt_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs+M6LCuc2/VwQKD6Zxo12Wd7CyXlCLWxMghCOYqtHaPGSk+bYLr/TDDD1kFyY0TVLFl8CH8+ksHCAI6e+2zefW7RYHVBcKB+J4FRuguXMhhoM7Rf65rrKHmJgi/gLPF9aBuKeK4sPaQa+PwCVHnVuu4aAYVwO0D+sioelXObTp2oqBN0TYv00kUca3pdTYy+rUy65FHvUfe3baLuB8+r3zNPL/1E9O091tJZXZn2k9c+fTkCDUC5jAz7F/Vilhdm1dR123ah1uJZC0VsDBbPT9waEO4OX8Ybh8jBNW18q2C9962eY0WpN43K8LIeCxyW5kdF8dABUhMsFOP9iP4f9wIDAQAB
  url: http://localhost:8080/realms/avaliador-credito/protocol/openid-connect/token
  clientId: avaliador-credito
