version: '3.4'
services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:21.1.2
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
      command: start-dev
      ports:
        - 8080:8080
      depends_on:
        - postgres
        
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmqq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - network
  cartao-db:
    image: postgres:15.3
    volumes:
      - cartao-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    networks:
      - network
      
  cliente-db:
    image: postgres:15.3
    volumes:
      - cliente-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5434:5432
    expose:
      - 5434
    networks:
      - network

  eureka-server:
    build: 
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    networks:
      - network

  cloud-gateway:
    build: 
      context: ./cloud-gateway
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-user:123456@eureka-server:8761/eureka
    networks:
      - network
  cliente-service:
    build: 
      context: ./cliente-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-user:123456@eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cliente-db/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SECURITY_JWT_EXPIRACAO=30
      - SECURITY_JWT_CHAVE_ASSINATURA=VrAhBEGD0zcsL8T6w3PmYDaFWtcW2vWz1cW57Lk05bSCnDrdYnTbJhGeBZdFufraJUNw0jFvbsmAAngSMYHPeqYH5nj7AeL2
    depends_on:
      - eureka-server
      - cliente-db
    networks:
      - network
      
  cartao-service:
    build: 
      context: ./cartao-service
      dockerfile: Dockerfile
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-user:123456@eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cartao-db/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SECURITY_JWT_EXPIRACAO=30
      - SECURITY_JWT_CHAVE_ASSINATURA=VrAhBEGD0zcsL8T6w3PmYDaFWtcW2vWz1cW57Lk05bSCnDrdYnTbJhGeBZdFufraJUNw0jFvbsmAAngSMYHPeqYH5nj7AeL2
    depends_on:
      - eureka-server
      - cartao-db
      - rabbitmq
    networks:
      - network

  avaliador-credito-service:
    container_name: avaliador-credito-service
    build: 
      context: ./avaliador-credito-service
      dockerfile: Dockerfile
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-user:123456@eureka-server:8761/eureka
      - SECURITY_JWT_EXPIRACAO=30
      - SECURITY_JWT_CHAVE_ASSINATURA=VrAhBEGD0zcsL8T6w3PmYDaFWtcW2vWz1cW57Lk05bSCnDrdYnTbJhGeBZdFufraJUNw0jFvbsmAAngSMYHPeqYH5nj7AeL2
    depends_on:
      - eureka-server
      - cartao-db
      - rabbitmq
    networks:
      - network
networks:
  network:
volumes:
    db:
    cartao-db:
    cliente-db:
    postgres_data: