server:
  port: 0
spring:
  application:
    name: cartao-service
  profiles:
    active:
      - cartao
  config:
    import: configserver:http://localhost:7000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://eureka-user:123456@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
springdoc:
  show-actuator: true
  api-docs:
   path: cartao-service/v3/api-docs
mq:
  queue:
    emissao-cartoes: emissao-cartoes
